AWSTemplateFormatVersion: 2010-09-09

Description: Nested stack for the GenmateField
  
Parameters:

# Environment configuration

  S3BucketName:
    AllowedPattern: ^[0-9a-z]+([0-9a-z-.]*[0-9a-z])*$
    ConstraintDescription: Bucket name can include numbers, lowercase letters, periods (.), and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name for the Nested Stacks. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String

  EnvironmentName:
    Description: The prefix name of the project. example) gf -> gfvpc
    Type: String

  EnvironmentStage:
    Type: String
    Description: The environment tag is used to designate the Environment Stage of the associated AWS resource.
    AllowedValues:
      - dev
      - test
      - pre-prod
      - prod
    Default: prod

# Network configuration

  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The list of Availability Zones to use for the subnets in the VPC.

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.21.0/24

  PrivateSubnet3CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.30.0/24

  PrivateSubnet4CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.31.0/24

# Domain configuration

  HostedZoneId:
    Description: Please select a Hosted Zone.(You must create domain certificates from us-east-1 before)
    Type: AWS::Route53::HostedZone::Id

  DomainName:
    Description: Please enter a domain name.
    Type: String
    Default: genmatefield.com

  WebSubDomainName:
    Description: Please enter a sub-domain name for web.
    Type: String
    Default: tool

  WebCertificateArn:
    Description: Please enter a arn for WEB cetrificate.
    Type: String

  APISubDomainName:
    Description: Please enter a sub-domain name for api.
    Type: String
    Default: api

# F/E CI/CD configuration

  GitHubOwner:
    Type: String
    Description: The username or org that owns the repo

  GitHubRepo:
    Type: String
    Description: The name of the repo as it appears in Github. ex) https://github.com/[GitHubRepo]

  GitHubBranch:
    Type: String
    Description: The branch to pull
    Default: main

  GitHubTokenSecretName:
    Type: String
    Description: The name of the Secrets Manager secret that contains a GitHub personal access token
    Default: Github

  GitHubTokenSecretKeyName:
    Type: String
    Description: The JSON key name of the Secrets Manager value
    Default: PersonalAccessToken

  WebsiteSourceDirectory:
    Type: String
    Description: The directory name in the repo where the website source is builded
    Default: dist

  SiteDeployAlertDetailType:
    Description: The level of detail to include in the notifications for this resource. (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarnotifications-notificationrule.html)
    Default: FULL
    Type: String
    AllowedValues:
      - FULL
      - BASIC

# Chatbot configuration

  SiteChatbotConfigurationName:
    Type: String
    Description: (Required) The name of the configuration.

  SiteSlackChannelId:
    Type: String
    Description: (Required) The ID of the Slack channel. To get the ID, open Slack, right click on the channel name in the left pane, then choose Copy Link. The channel ID is the 9-character string at the end of the URL. For example, ABCBBLZZZ.

  SiteSlackWorkspaceId:
    Type: String
    Description: (Required) The ID of the Slack workspace authorized with AWS Chatbot. To get the workspace ID, you must perform the initial authorization flow with Slack in the AWS Chatbot console. Then you can copy and paste the workspace ID from the console. For more details, see steps 1-4 in Setting Up AWS Chatbot with Slack in the AWS Chatbot User Guide.

# API configuration

  # ParentWASStack:
  #   Description: 'Provide Stack name of parent Amazon Linux bastion host stack based on VPC-SSH-Bastion yaml template. Refer Cloudformation dashboard in AWS Console to get this.'
  #   Type: String
  #   MinLength: '1'
  #   MaxLength: '128'
  #   AllowedPattern: '^[a-zA-Z]+[0-9a-zA-Z\-]*$'
  
  # DB configuration

  DBName:
    Description: Database Name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_]*$" 
    ConstraintDescription: Must start with a letter. Only numbers, letters, and _ accepted. max length 64 characters 
    
  DBUsername:
    Description: Database master username(No admin)
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, and _ accepted. max length 16 characters, MasterUsername admin cannot be used as it is a reserved word used by the engine 
     
  DBEngineVersion:
    Description: Select Database Engine Version
    Type: String
    Default: 13.7
    AllowedValues:
      - 11.16
      - 12.11
      - 13.7
      - 14.3
     
  DBInstanceClass:
    Default: db.t4g.medium
    Description: Database Instance Class
    Type: String
    AllowedValues:
    - db.t4g.medium
    - db.t4g.large
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    - db.r5.4xlarge
    - db.r5.8xlarge
    - db.r5.12xlarge
    - db.r5.16xlarge
    - db.r5.24xlarge
    - db.r6g.large
    - db.r6g.xlarge
    - db.r6g.2xlarge
    - db.r6g.4xlarge
    - db.r6g.8xlarge
    - db.r6g.12xlarge
    - db.r6g.16xlarge
    - db.x2g.large
    - db.x2g.xlarge
    - db.x2g.2xlarge
    - db.x2g.4xlarge
    - db.x2g.8xlarge
    - db.x2g.12xlarge
    - db.x2g.16xlarge
    
  NotificationList:
    Type: String
    Description: The Email notification list is used to configure a SNS topic for sending cloudwatch alarm and RDS Event notifications
    AllowedPattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    ConstraintDescription: provide a valid email address.
 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Environment Configuration"
        Parameters:
          - EnvironmentName
          - EnvironmentStage
          - S3BucketName
          - GitHubTokenSecretName
          - GitHubTokenSecretKeyName
      -
        Label:
          default: "Domain Configuration"
        Parameters:
          - HostedZoneId
          - DomainName
          - WebSubDomainName
          - APISubDomainName
          - WebCertificateArn
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PrivateSubnet3CIDR
          - PrivateSubnet4CIDR
          - AvailabilityZones
      -
        Label:
          default: "Frontend CI/CD Configuration"
        Parameters:
          - GitHubOwner
          - GitHubRepo
          - GitHubBranch
          - WebsiteSourceDirectory
          - SiteDeployAlertDetailType
          - SiteChatbotConfigurationName
          - SiteSlackChannelId
          - SiteSlackWorkspaceId
      -
        Label:
          default: "DB Configuration"
        Parameters:
          - DBName
          - DBUsername
          - DBEngineVersion
          - DBInstanceClass
          - NotificationList

    ParameterLabels:
      EnvironmentName:
        default: "What is the project prefix?"
      S3BucketName:
        default: "What is the name of the bucket where the template is stored?"
      DomainName:
        default: "What is your site name of root domain? ex) example.com (no www)"
      WebSubDomainName:
        default: "What is the site domain name? ex) www.example.com"
      APISubDomainName:
        default: "What is the API domain name? ex) api.example.com"
      WebCertificateArn:
        default: "What is the certificate ARN for setting up HTTPS?"


    
Resources:
  VpcStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/vpc.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AvailabilityZones:
          Fn::Join:
            - ','
            - !Ref AvailabilityZones
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
        PrivateSubnet4CIDR: !Ref PrivateSubnet4CIDR
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  DnsStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/dns.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DomainName: !Ref DomainName
        WebSubDomainName: !Ref WebSubDomainName
        APISubDomainName: !Ref APISubDomainName
        HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  WebStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/web.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DomainName: !Ref DomainName
        WebSubDomainName: !Ref WebSubDomainName
        HostedZoneId: !Sub
          - ${NestedStackName}-HostedZoneID
          - { NestedStackName: !Select [1, !Split ["/", !Ref DnsStack]] }
        CertificateArn: !Ref WebCertificateArn
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  SitePipelineStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/site-pipeline.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        GitHubTokenSecretName: !Ref GitHubTokenSecretName
        GitHubTokenSecretKeyName: !Ref GitHubTokenSecretKeyName
        WebsiteSourceDirectory: !Ref WebsiteSourceDirectory
        WebsiteBucket: !Sub
          - ${NestedStackName}-WebsiteBucket
          - { NestedStackName: !Select [1, !Split ["/", !Ref WebStack]] }
        AlertDetailType: !Ref SiteDeployAlertDetailType
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  ChatbotStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/chatbot.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ConfigurationName: !Ref SiteChatbotConfigurationName
        SlackChannelId: !Ref SiteSlackChannelId
        SlackWorkspaceId: !Ref SiteSlackWorkspaceId 
        SnsTopicArns: !Sub
          - ${NestedStackName}-SNSTopicArn
          - { NestedStackName: !Select [1, !Split ["/", !Ref SitePipelineStack]] }
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  DBStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/aurora-postgres-db-cluster.yml
      TimeoutInMinutes: 20
      Parameters:
        ParentVPCStack: !Sub
          - ${NestedStackName}
          - { NestedStackName: !Select [1, !Split ["/", !Ref VpcStack]] }
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername 
        DBEngineVersion: !Ref DBEngineVersion 
        DBInstanceClass: !Ref DBInstanceClass 
        LambdaBootStrapS3Bucket: !Ref S3BucketName
        EnvironmentStage: !Ref EnvironmentStage
        NotificationList: !Ref NotificationList
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
