AWSTemplateFormatVersion: 2010-09-09

Description: Nested stack for the GenmateField
  
Parameters:

# Environment configuration

  S3BucketName:
    AllowedPattern: ^[0-9a-z]+([0-9a-z-.]*[0-9a-z])*$
    ConstraintDescription: Bucket name can include numbers, lowercase letters, periods (.), and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name for the Nested Stacks. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String

  EnvironmentName:
    Description: The prefix name of the project. ex) gf -> gfvpc
    Type: String

# Network configuration

  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The list of Availability Zones to use for the subnets in the VPC.

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.21.0/24

  PrivateSubnet3CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.30.0/24

  PrivateSubnet4CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.192.31.0/24

# Domain configuration

  DomainName:
    Description: Please enter a domain name.
    Type: String
    Default: genmatefield.com

  WebSubDomainName:
    Description: Please enter a sub-domain name for web.
    Type: String
    Default: tool

  WebCertificateArn:
    Description: Please enter a arn for WEB cetrificate.
    Type: String

  APISubDomainName:
    Description: Please enter a sub-domain name for api.
    Type: String
    Default: api

# F/E CI/CD configuration

  GitHubOwner:
    Type: String
    Description: The username or org that owns the repo

  GitHubRepo:
    Type: String
    Description: The name of the repo as it appears in Github. ex) https://github.com/[GitHubRepo]

  GitHubBranch:
    Type: String
    Description: The branch to pull
    Default: main

  GitHubTokenSecretName:
    Type: String
    Description: The name of the Secrets Manager secret that contains a GitHub personal access token
    Default: Github

  GitHubTokenSecretKeyName:
    Type: String
    Description: The JSON key name of the Secrets Manager value
    Default: PersonalAccessToken

  WebsiteSourceDirectory:
    Type: String
    Description: The directory name in the repo where the website source is builded
    Default: dist


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Environment Configuration"
        Parameters:
          - EnvironmentName
          - S3BucketName
          - GitHubTokenSecretName
          - GitHubTokenSecretKeyName
      -
        Label:
          default: "Domain Configuration"
        Parameters:
          - DomainName
          - WebSubDomainName
          - APISubDomainName
          - WebCertificateArn
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PrivateSubnet3CIDR
          - PrivateSubnet4CIDR
          - AvailabilityZones
      -
        Label:
          default: "Frontend CI/CD Configuration"
        Parameters:
          - GitHubOwner
          - GitHubRepo
          - GitHubBranch
          - WebsiteSourceDirectory

    ParameterLabels:
      EnvironmentName:
        default: "What is the project prefix?"
      S3BucketName:
        default: "What is the name of the bucket where the template is stored?"
      DomainName:
        default: "What is your site name of root domain? ex) example.com (no www)"
      WebSubDomainName:
        default: "What is the site domain name? ex) www.example.com"
      APISubDomainName:
        default: "What is the API domain name? ex) api.example.com"
      WebCertificateArn:
        default: "What is the certificate ARN for setting up HTTPS?"

Resources:
  VpcStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/vpc.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AvailabilityZones:
          Fn::Join:
            - ','
            - !Ref AvailabilityZones
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
        PrivateSubnet4CIDR: !Ref PrivateSubnet4CIDR
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  DnsStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/dns.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DomainName: !Ref DomainName
        WebSubDomainName: !Ref WebSubDomainName
        APISubDomainName: !Ref APISubDomainName
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  WebStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/web.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DomainName: !Ref DomainName
        WebSubDomainName: !Ref WebSubDomainName
        HostedZoneId: !Sub
          - ${NestedStackName}-HostedZoneID
          - { NestedStackName: !Select [1, !Split ["/", !Ref DnsStack]] }
        CertificateArn: !Ref WebCertificateArn
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  SitePipelineStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/site-pipeline.yml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        GitHubTokenSecretName: !Ref GitHubTokenSecretName
        GitHubTokenSecretKeyName: !Ref GitHubTokenSecretKeyName
        WebsiteSourceDirectory: !Ref WebsiteSourceDirectory
        WebsiteBucket: !Sub
          - ${NestedStackName}-WebsiteBucket
          - { NestedStackName: !Select [1, !Split ["/", !Ref WebStack]] }
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName


